# Generated by Django 4.2.1 on 2023-05-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='Nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='proyecto',
        ),
    ]
