# Generated by Django 4.2.1 on 2023-05-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0002_equipo_rename_nombre_equipos_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
